name: UHC
main: games.chocola.minazukii.uhc.UHC
version: 1.1.0
api-version: 1.18
depend: [GameUtils]
author: MinazukiiChocola
commands:
  forceend:
    description: force end a game
  uhcteam:
    description: team up in uhc game